name: Build and deploy documentation

on:

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Method to manually build and deploy docs'
        required: false
        default: false

jobs:
  # This job is called test_docs.
  unit_test_and_docs:
    # Recommended if you intend to make multiple deployments in quick succession
    concurrency: ci-${{ github.ref }}
    # Run on Ubuntu
    runs-on: ubuntu-latest
    # Necessary to prevent mpi tests failing due to lack of slots
    env:
      OMPI_MCA_btl: self,tcp
      OMPI_MCA_rmaps_base_oversubscribe: 1
    # Ensures conda environment is initialized for all steps
    defaults:
      run:
        shell: bash -l {0}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # real versions
          - NAME: Real
            OPTIONAL: 'default'
            INTERFACE: 'interface'
            PUBLISH_DOCS: true

    name: FUNtoFEM ${{ matrix.NAME }} Build/Test

    steps:
      - name: Display run details
        run: |
          echo "=============================================================";
          echo "Run #${GITHUB_RUN_NUMBER}";
          echo "Run ID: ${GITHUB_RUN_ID}";
          echo "Testing: ${GITHUB_REPOSITORY}";
          echo "Triggered by: ${GITHUB_EVENT_NAME}";
          echo "Initiated by: ${GITHUB_ACTOR}";
          echo "=============================================================";

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - name: Install FUNtoFEM
        run: |
          echo "=============================================================";
          echo "Install FUNtoFEM";
          echo "=============================================================";
          export F2F_DIR=${GITHUB_WORKSPACE};
          echo "F2F_DIR=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
          cd $F2F_DIR;
          cp Makefile.in.info Makefile.in;
          make ${{ matrix.OPTIONAL }} F2F_DIR=$F2F_DIR METIS_INCLUDE=-I${CONDA_PREFIX}/include/ METIS_LIB="-L${CONDA_PREFIX}/lib/ -lmetis";
          cd $F2F_DIR;
          make ${{ matrix.INTERFACE }};

      - name: Build docs
        run: |
          cd ${GITHUB_WORKSPACE}/docs;
          make html BUILDDIR=.;
          cd html;
          zip -r ../f2f-docs.zip .;
      - name: Upload docs
        if: ${{ matrix.PUBLISH_DOCS }}
        uses: actions/upload-artifact@v2
        with:
          name: f2f-docs
          path: docs/f2f-docs.zip
      - name: Deploy docs
        if: ${{ matrix.PUBLISH_DOCS }}
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to
          folder: docs/html/ # The folder the action should deploy